
### http_serve
GET http://127.0.0.1:8081

### minigix

GET http://127.0.0.1:8080 HTTP/1.1
Connection: keep-alive
Keep-Alive: timeout=5, max=1000

### minigix
GET http://127.0.0.1:8080

### minigix
GET http://127.0.0.1:8080 HTTP/2.0

### shortener
GET http://127.0.0.1:3000

### shortener redirect
GET http://127.0.0.1:3000/X_2C4H HTTP/1.1

### shortener shortener
POST http://127.0.0.1:3000/shortener HTTP/1.1
content-type: application/json

{
    "uri":"www.roblox.com"
}
